name: Build and Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Test
        run: |
          ./gradlew clean build

  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 26, 27, 28, 29, 30, 31 ]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          script: ./gradlew connectedAndroidTest