name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          cache: gradle

      - name: Build
        run: |
          ./gradlew clean build

      - name: Decode Secret Key Ring
        uses: timheuer/base64-to-file@v1.1
        with:
          fileName: 'secretkeyring.gpg'
          fileDir: '.'
          encodedString: ${{ secrets.SECRET_RING_KEY }}

      - name: Publish
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: "../secretkeyring.gpg"
        run: |
          ./gradlew publishReleasePublicationToSonatypeRepository